version: "3"
services:
  goangular-app:
    build: 
      context: .
      dockerfile: Dockerfile.app
  nginx:    
    image: nginx
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./ui/dist/goangular-app:/var/www/html    
    ports:
      - "8080:80"